# Generated by Codex on 2026-06-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("code", models.CharField(blank=True, max_length=8, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180)),
                ("kind", models.CharField(choices=[("county", "County"), ("city", "City"), ("municipality", "Municipality"), ("town", "Town"), ("area", "Area"), ("sub_location", "Sub-location"), ("region", "Region"), ("province", "Province"), ("district", "District")], max_length=24)),
                ("level", models.PositiveSmallIntegerField(default=1)),
                ("full_path", models.CharField(max_length=600, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="products.country")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="products.location")),
            ],
            options={"ordering": ["full_path"]},
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="products", to="products.country"),
        ),
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="products", to="products.location"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("country", "parent", "name"), name="unique_location_name_per_parent"),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("country", "full_path"), name="unique_location_full_path_per_country"),
        ),
    ]
