# Generated by Codex on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_attributedefinition_attributeoption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="country",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="products", to="products.country"),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="products", to="products.location"),
        ),
    ]
