# Generated by Codex on 2026-06-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_country_location_nullable"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE products_product DROP COLUMN location;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
