# Generated by Django 4.2.16 on 2026-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_reaction_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='viewer_count_live',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
