# Generated by Django 4.2.16 on 2026-06-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_add_total_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='viewer_count_cached',
        ),
    ]
