# Generated by Django 4.2.16 on 2026-06-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_remove_livesession_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
