# Generated by Codex on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_directmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directmessage",
            name="body",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="dm_attachments/"),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="attachment_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="directmessage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="users.directmessage",
            ),
        ),
    ]
